version: "1.0"
services:
  #Creazione container database
  db:
    image: mysql
    deploy:
      replicas: 2
  #Creazione container server
  server:
    image: webserver
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:80"
