version: '3'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
      VIRTUAL_HOST: joomla.local
      VIRTUAL_PORT: 80
    networks:
      - nginx_proxy 
      - default 
  joomladb:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - default
networks:
  nginx_proxy:
    external: true
  default: