
services:

  wordpress:
    image: wordpress
    restart: always
    #ports:
    #  - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpUser
      WORDPRESS_DB_PASSWORD: db
      WORDPRESS_DB_NAME: Docker
      VIRTUAL_HOST: wordpress.local
      VIRTUAL_PORT: 80
    volumes:
      - wordpress:/var/www/html
    networks:
      - nginx-proxy

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: Docker
      MYSQL_USER: wpUser
      MYSQL_PASSWORD: db
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:

networks:
  nginx-proxy:
    external: true
